### add a new member
POST http://localhost:5000/api/v1/auth/signup
content-type: application/json

{
    "f_name": "John",
    "l_name": "Smith",
    "email": "john.smith@gmail.com",
    "mobile": "9999999999",
    "password": "password999"
}

### login
POST http://localhost:5000/api/v1/auth/login
content-type: application/json

{
    "email": "adam.smith@gmail.com",
    "password": "password123"
}

### retrieve all members 
GET http://localhost:5000/api/v1/member

### retrieve a specific member by ID
GET http://localhost:5000/api/v1/member/1


### enter profile page
GET http://localhost:5000/api/v1/member/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTY1MzI1NiwiZXhwIjoxNzI5NjUzMjg2fQ.2Y5SMaz2NnQUO5IPrqxGKMPPwlg871gpJisLz71GYS4

### edit profile info
PUT http://localhost:5000/api/v1/member/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTY0NDgwNSwiZXhwIjoxNzI5NjQ2NjA1fQ.LnHmIp0euaon5jbqOtZwrWszMpM_UiW3CAbG6FcoWyo

{
    "f_name": "Jane"
}

### delete member
DELETE http://localhost:5000/api/v1/member/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTY0NDgwNSwiZXhwIjoxNzI5NjQ2NjA1fQ.LnHmIp0euaon5jbqOtZwrWszMpM_UiW3CAbG6FcoWyo

### add workout
POST http://localhost:5000/api/v1/member/workout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTY1NTI5NCwiZXhwIjoxNzI5NjU3MDk0fQ.e14Hf3vltwRvTgaVjD8Y2chhXHW8ryQlHYDDUMY9of4

{
    "name": "Swimming",
    "duration_min": 60,
    "distance_km": 1.5
}

### view workouts
GET http://localhost:5000/api/v1/member/workout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTY1NTI5NCwiZXhwIjoxNzI5NjU3MDk0fQ.e14Hf3vltwRvTgaVjD8Y2chhXHW8ryQlHYDDUMY9of4

### view specific workout
GET http://localhost:5000/api/v1/member/workout/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTY1NTI5NCwiZXhwIjoxNzI5NjU3MDk0fQ.e14Hf3vltwRvTgaVjD8Y2chhXHW8ryQlHYDDUMY9of4

### edit workout info
PUT http://localhost:5000/api/v1/member/workout/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTY1MjEyMSwiZXhwIjoxNzI5NjUzOTIxfQ.RDaHnLZyit-RFPjHhwitUjN4VIIJPI6z4kd6QcqhTdE

{
    "name": "Walking"
}

### delete specific workout
DELETE http://localhost:5000/api/v1/member/workout/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTY1MjEyMSwiZXhwIjoxNzI5NjUzOTIxfQ.RDaHnLZyit-RFPjHhwitUjN4VIIJPI6z4kd6QcqhTdE


### add nutrition of a specific member
POST http://localhost:5000/api/v1/member/nutrition
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTY1NTI5NCwiZXhwIjoxNzI5NjU3MDk0fQ.e14Hf3vltwRvTgaVjD8Y2chhXHW8ryQlHYDDUMY9of4

{
    "name": "Turkey Sandwich",
    "calories": 850
}

### retrieve all nutrition data of a specific member
GET http://localhost:5000/api/v1/member/nutrition
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTY1NzM0MCwiZXhwIjoxNzI5NjU5MTQwfQ.6OO2Pbt-xQ0iRXsEU-KWyDxGflZiXnYpE2jkvLsFrkA

### retrieve speciifc nutrition data of a specific member
GET http://localhost:5000/api/v1/member/nutrition/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTY1NzM0MCwiZXhwIjoxNzI5NjU5MTQwfQ.6OO2Pbt-xQ0iRXsEU-KWyDxGflZiXnYpE2jkvLsFrkA

### edit specific nutrition data of a specific member
PUT http://localhost:5000/api/v1/member/nutrition/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTY1NzM0MCwiZXhwIjoxNzI5NjU5MTQwfQ.6OO2Pbt-xQ0iRXsEU-KWyDxGflZiXnYpE2jkvLsFrkA

{
    "fat": 5.6
}

### delete specific nutrition data of a specific member
DELETE http://localhost:5000/api/v1/member/nutrition/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTY1NzM0MCwiZXhwIjoxNzI5NjU5MTQwfQ.6OO2Pbt-xQ0iRXsEU-KWyDxGflZiXnYpE2jkvLsFrkA