### add a new member
POST http://localhost:5000/api/v1/auth/signup
content-type: application/json

{
    "f_name": "Max",
    "l_name": "Smith",
    "email": "max.smith@gmail.com",
    "mobile": "1234567890",
    "password": "password890"
}

### login
POST http://localhost:5000/api/v1/auth/login
content-type: application/json

{
    "email": "max.smith@gmail.com",
    "password": "password890"
}

### enter profile page
GET http://localhost:5000/api/v1/member/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY

### edit profile info
PUT http://localhost:5000/api/v1/member/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY

{
    "body_weight": 70.5
}

### delete member
DELETE http://localhost:5000/api/v1/member/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY

### add workout
POST http://localhost:5000/api/v1/member/workout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY

{
    "name": "Running",
    "duration_min": 60,
    "distance_km": 5
}

### view workouts
GET http://localhost:5000/api/v1/member/workout?week=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY

### view specific workout
GET http://localhost:5000/api/v1/member/workout/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY

### edit workout info
PUT http://localhost:5000/api/v1/member/workout/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY

{
    "name": "Walking"
}

### delete specific workout
DELETE http://localhost:5000/api/v1/member/workout/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY


### add nutrition of a specific member
POST http://localhost:5000/api/v1/member/nutrition
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY

{
    "name": "Turkey Sandwich",
    "calories": 850
}

### retrieve all nutrition data of a specific member
GET http://localhost:5000/api/v1/member/nutrition?date=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY

### retrieve speciifc nutrition data of a specific member
GET http://localhost:5000/api/v1/member/nutrition/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY

### edit specific nutrition data of a specific member
PUT http://localhost:5000/api/v1/member/nutrition/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY

{
    "fat": 5.6
}

### delete specific nutrition data of a specific member
DELETE http://localhost:5000/api/v1/member/nutrition/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY

### add a goal of a specific member
POST http://localhost:5000/api/v1/member/goal
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY

{
    "goal_type": "Workout distance",
    "weekly_goal": 5,
    "total_duration": 8
}

### retrieve all goals of a specific member
GET http://localhost:5000/api/v1/member/goal
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY

### retrieve a specific goal of a specific member
GET http://localhost:5000/api/v1/member/goal/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY

### update a specific goal of a specific member
PUT  http://localhost:5000/api/v1/member/goal/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY

{
    "weekly_goal": 4500
}

### delete a specific goal of a specific member
DELETE http://localhost:5000/api/v1/member/goal/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaXNfcHJlbWl1bSI6ZmFsc2UsImlhdCI6MTcyOTcyMTAxNiwiZXhwIjoxNzI5NzI0NjE2fQ.bU9-BrN1oB8qXEa3iwJ9R6SoVWHCc21NDKZNiBjSUoY